// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:quickserve_mobile/config/firebase/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7HJ0h6ytvAY10bFOjBESokqCjEzGH6mI',
    appId: '1:365021745349:web:6c532f0d1b31d289e4e0ac',
    messagingSenderId: '365021745349',
    projectId: 'quickserve-78e40',
    authDomain: 'quickserve-78e40.firebaseapp.com',
    storageBucket: 'quickserve-78e40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgCYCZBAHXid1cyFK4-BcHos33Txo1G8',
    appId: '1:365021745349:android:f1422dfcbc21bf1ee4e0ac',
    messagingSenderId: '365021745349',
    projectId: 'quickserve-78e40',
    storageBucket: 'quickserve-78e40.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq76M0E215bKoXCX6zSYn4Tfalkf5veQ4',
    appId: '1:365021745349:ios:8b95277f45bd82cee4e0ac',
    messagingSenderId: '365021745349',
    projectId: 'quickserve-78e40',
    storageBucket: 'quickserve-78e40.firebasestorage.app',
    iosBundleId: 'com.example.quickServe',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq76M0E215bKoXCX6zSYn4Tfalkf5veQ4',
    appId: '1:365021745349:ios:8b95277f45bd82cee4e0ac',
    messagingSenderId: '365021745349',
    projectId: 'quickserve-78e40',
    storageBucket: 'quickserve-78e40.firebasestorage.app',
    iosBundleId: 'com.example.quickServe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7HJ0h6ytvAY10bFOjBESokqCjEzGH6mI',
    appId: '1:365021745349:web:c2f84cff44d742b2e4e0ac',
    messagingSenderId: '365021745349',
    projectId: 'quickserve-78e40',
    authDomain: 'quickserve-78e40.firebaseapp.com',
    storageBucket: 'quickserve-78e40.firebasestorage.app',
  );
}
